/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'is.keith.fc.message'

type $nsid = typeof $nsid

export { $nsid }

/** A friend club message: a short text and a 2-second video, optionally cross-posted to Bluesky and set to expire. */
type Main = {
  $type: 'is.keith.fc.message'
  text: string
  video?: l.BlobRef

  /**
   * Link to cross-posted Bluesky post, if any
   */
  blueskyPostUri?: l.AtUriString

  /**
   * When this message should be deleted (optional)
   */
  expiresAt?: l.DatetimeString
  createdAt: l.DatetimeString
}

export type { Main }

/** A friend club message: a short text and a 2-second video, optionally cross-posted to Bluesky and set to expire. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxLength: 255 }),
    video: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['video/mp4'], maxSize: 10000000 }),
    ),
    blueskyPostUri: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    expiresAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
